In [1]:
import pandas as pd
import warnings
import os
warnings.filterwarnings('ignore')

In [2]:
parent_dir = os.path.dirname(os.getcwd())
data_path = os.path.join(parent_dir, 'data', 'datasets')
out_path = os.path.join(parent_dir, 'data', 'train')

In [4]:
dataset = pd.read_csv(os.path.join(data_path, 'dataset.csv'))
champ_role_metrics = pd.read_csv(os.path.join(data_path, 'champ_role_metrics.csv'))
champ_metrics = pd.read_csv(os.path.join(data_path, 'champ_metrics.csv'))

In [7]:
temp = dataset.copy()

In [8]:
temp

,GOLDEARNED,TOTALMINIONSKILLED,WIN,KILLS,ASSISTS,DEATHS,CHAMPION,VISIONSCORE,PUUID,TOTALDAMAGEDEALTTOCHAMPIONS,SUMMONERNAME,GAMEVERSION,REGION,MATCH_ID,ROLE
0,14425,194,False,14,5,7,Kassadin,17,phduyQLB8gBjUerFwiVOtyLLHE9jxw7Jq7dwab_CtRddAv...,33426,Borke,11.14.384.6677,TR1,1201957752_TR1,top
1,12920,177,True,3,13,6,Fiora,17,SgQ5hm74vmXVDB3GIt3ka7gaBXFpNnT3PbHU8TbjEk5PJ8...,12092,Nora Durst,11.14.384.6677,TR1,1201957752_TR1,top
2,13483,221,False,7,3,6,Yone,20,m7Sxq9HxRKLIgf0n0QOKhfHq8jNMZ-k1VhW_jcb307sUya...,20604,Fightêr Yone,11.14.384.6677,TR1,1201957752_TR1,middle
3,11375,167,True,4,15,7,Corki,27,pa-g2VGIEJn7CJCYYQU1PaHUqjS9pB7M4PsDcjM3ac5ysM...,30150,AM SORİİ HE,11.14.384.6677,TR1,1201957752_TR1,middle
4,11320,197,False,5,10,12,Kaisa,17,_WeC06P4yIMW7ZMWi6bmwCagXp7c7bxxGv6nNW4--SGqXp...,16689,º J İ N X º,11.14.384.6677,TR1,1201957752_TR1,bottom
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1312243,9282,30,True,5,16,6,Alistar,59,6qh4YYzZ8ZH0U4NKCF61J54qbgtXdq0F3LtfKyE5dKG1Q0...,9842,didvyriojega,11.9.372.2066,EUW1,5262352897_EUW1,utility
1312244,8236,10,False,2,5,7,LeeSin,19,9LxP5BcqYdM8blcITug2TOu9swsSirIRKusC9zMNW815tB...,8805,ALLEY JUICE,11.9.372.2066,EUW1,5262352897_EUW1,jungle
1312245,10770,32,True,5,16,5,FiddleSticks,67,4lFMD-GpyAOEewqSmPQ08DgLo3yZ14RaWvojo_X1Sc7AEU...,18490,chair material,11.9.372.2066,EUW1,5262352897_EUW1,jungle
1312246,6249,124,False,1,1,3,Shen,17,gAw8AlzR3QOzpfepxrI5rRuHorelwKxmVQ55f4QXAZiazU...,3470,Big Al Esq,11.9.372.2066,EUW1,5261950371_EUW1,top
1312247,8834,161,True,3,3,2,Darius,14,mJOdKKegN2SJFcnrfTEg74a6NH-zvyMlaX100mqKdqvxQo...,7865,Therkima,11.9.372.2066,EUW1,5261950371_EUW1,top

In [16]:
match_counts = dataset.MATCH_ID.value_counts().reset_index(name='count')
match_counts

                 index  count
0       1201957752_TR1     10
1       1105779563_LA1     10
2       2326246890_BR1     10
3       2326330848_BR1     10
4       2326635837_BR1     10
...                ...    ...
133509  3955949371_NA1      2
133510  3956149022_NA1      2
133511  3956129184_NA1      2
133512  3956169265_NA1      2
133513  2163291036_BR1      2

[133514 rows x 2 columns]

In [42]:
matches_less_than_10 = match_counts[match_counts['count'] != 10]['index'].tolist()

In [44]:
len(matches_less_than_10)

6106

In [45]:
temp = dataset[~dataset.MATCH_ID.isin(matches_less_than_10)]

In [46]:
temp

,GOLDEARNED,TOTALMINIONSKILLED,WIN,KILLS,ASSISTS,DEATHS,CHAMPION,VISIONSCORE,PUUID,TOTALDAMAGEDEALTTOCHAMPIONS,SUMMONERNAME,GAMEVERSION,REGION,MATCH_ID,ROLE
0,14425,194,False,14,5,7,Kassadin,17,phduyQLB8gBjUerFwiVOtyLLHE9jxw7Jq7dwab_CtRddAv...,33426,Borke,11.14.384.6677,TR1,1201957752_TR1,top
1,12920,177,True,3,13,6,Fiora,17,SgQ5hm74vmXVDB3GIt3ka7gaBXFpNnT3PbHU8TbjEk5PJ8...,12092,Nora Durst,11.14.384.6677,TR1,1201957752_TR1,top
2,13483,221,False,7,3,6,Yone,20,m7Sxq9HxRKLIgf0n0QOKhfHq8jNMZ-k1VhW_jcb307sUya...,20604,Fightêr Yone,11.14.384.6677,TR1,1201957752_TR1,middle
3,11375,167,True,4,15,7,Corki,27,pa-g2VGIEJn7CJCYYQU1PaHUqjS9pB7M4PsDcjM3ac5ysM...,30150,AM SORİİ HE,11.14.384.6677,TR1,1201957752_TR1,middle
4,11320,197,False,5,10,12,Kaisa,17,_WeC06P4yIMW7ZMWi6bmwCagXp7c7bxxGv6nNW4--SGqXp...,16689,º J İ N X º,11.14.384.6677,TR1,1201957752_TR1,bottom
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1312243,9282,30,True,5,16,6,Alistar,59,6qh4YYzZ8ZH0U4NKCF61J54qbgtXdq0F3LtfKyE5dKG1Q0...,9842,didvyriojega,11.9.372.2066,EUW1,5262352897_EUW1,utility
1312244,8236,10,False,2,5,7,LeeSin,19,9LxP5BcqYdM8blcITug2TOu9swsSirIRKusC9zMNW815tB...,8805,ALLEY JUICE,11.9.372.2066,EUW1,5262352897_EUW1,jungle
1312245,10770,32,True,5,16,5,FiddleSticks,67,4lFMD-GpyAOEewqSmPQ08DgLo3yZ14RaWvojo_X1Sc7AEU...,18490,chair material,11.9.372.2066,EUW1,5262352897_EUW1,jungle
1312246,6249,124,False,1,1,3,Shen,17,gAw8AlzR3QOzpfepxrI5rRuHorelwKxmVQ55f4QXAZiazU...,3470,Big Al Esq,11.9.372.2066,EUW1,5261950371_EUW1,top
1312247,8834,161,True,3,3,2,Darius,14,mJOdKKegN2SJFcnrfTEg74a6NH-zvyMlaX100mqKdqvxQo...,7865,Therkima,11.9.372.2066,EUW1,5261950371_EUW1,top